template: Hello, %s!
defaultName: Stranger
database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/example

#logging:
#  level: DEBUG
#  loggers:
#    "io.dropwizard": DEBUG
#  appenders:
#  - type: console
